teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.3
  scale_linear_turbo: 1.0
  axis_angular: 0
  scale_angular: 0.7
  scale_angular_turbo: 2.0
  enable_button: 4
  enable_turbo_button: 5
joy_node:
  deadzone: 0.3
  autorepeat_rate: 40

